name: phro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  yaml: ^3.1.3
  yaml_writer: ^2.1.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  uuid: ^4.5.3
  dart_openai: ^6.1.1
  openai_dart: ^4.3.0
  http: ^1.6.0
  flutter_markdown: ^0.7.7+1
  html2md: ^1.3.2
  flutter_highlighter: ^0.1.1
  highlight: ^0.7.0
  markdown: ^7.3.1
  flutter_riverpod: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.5
  hive_ce_test: ^2.0.0

flutter:
  uses-material-design: true
